version: '3.8'
services:
  server:
    build:
      context: ./CarWash_Server
      dockerfile: Dockerfile
    container_name: topaz-server
    ports:
      - "9090:9090"
    networks:
      mynetwork:
    depends_on:
      - db
    environment:
      - TZ=Asia/Novosibirsk
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/topaz_application
      - POSTGRES_USER=topaz_application
      - POSTGRES_PASSWORD=NSU_UNIVERSITY_123_321_ZNAEM_VICHMAT
  db:
    image: postgres:13.7-alpine
    container_name: topaz-db
    ports:
      - "5432:5432"
    networks:
      mynetwork:
    environment:
      - TZ=Asia/Novosibirsk
      - POSTGRES_DB=topaz_application
      - POSTGRES_PASSWORD=NSU_UNIVERSITY_123_321_ZNAEM_VICHMAT
      - POSTGRES_USER=topaz_application
    volumes:
      - topaz-db-data:/var/lib/postgresql/data

  react_app:
    build:
      context: ./CarWash_Site
      dockerfile: Dockerfile
    container_name: topaz-site
    ports:
      - "3000:3000"
    networks:
      mynetwork:
    environment:
      - TZ=Asia/Novosibirsk
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge

volumes:
  topaz-db-data:
