version: '3.8'
services:
  server:
    build:
      context: ./CarWash_Server
      dockerfile: Dockerfile
    container_name: misha-server
    ports:
      - "9090:9090"
    networks:
      mynetwork:
    depends_on:
      - db
    environment:
      - TZ=Asia/Novosibirsk
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123zxccxz321
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n

  db:
    image: postgres:13.7-alpine
    container_name: misha-db
    ports:
      - "1890:1890"
    networks:
      mynetwork:
    environment:
      - TZ=Asia/Novosibirsk
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123zxccxz321
    volumes:
      - misha-db-data:/var/lib/postgresql/data

  react_app:
    build:
      context: ./CarWash_Site
      dockerfile: Dockerfile
    container_name: misha-site
    ports:
      - "3000:3000"
    networks:
      mynetwork:
    environment:
      - TZ=Asia/Novosibirsk
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge

volumes:
  misha-db-data:
